# Generated by Django 5.1 on 2024-08-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('dob', models.DateTimeField()),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
